export const GET_SHIPS_REQUEST = 'GET_SHIPS_REQUEST';
export const GET_SHIPS_SUCCESS = 'GET_SHIPS_SUCCESS';
export const GET_SHIPS_FAILURE = 'GET_SHIPS_FAILURE';

export const GET_FILTERS_REQUEST = 'GET_FILTERS_REQUEST';
export const GET_FILTERS_SUCCESS = 'GET_FILTERS_SUCCESS';
export const GET_FILTERS_FAILURE = 'GET_FILTERS_FAILURE';
